[project]
name = "recipe-manager"
version = "0.1.0"
description = "Used simple OOP concepts to make something fun and structured."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
authors = [
    { name = "Sadhana Uprety" }
]
